// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: protobuf/tensorflow/core/framework/op_gen_overrides.proto

/*
	Package tensorflow is a generated protocol buffer package.

	It is generated from these files:
		protobuf/tensorflow/core/framework/op_gen_overrides.proto

	It has these top-level messages:
		OpGenOverride
		OpGenOverrides
*/
package tensorflow

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import tensorflow5 "github.com/d4l3k/pok/tensorflow/core/framework"

import fmt "fmt"
import strings "strings"
import reflect "reflect"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// Used to override the default API & behavior in the generated code
// for client languages, from what you would get from the OpDef alone.
// This is so we can evolve the API while remaining backwards
// compatible when interpretting old graphs.  Overrides go in an
// "op_gen_overrides.pbtxt" file with a text-format OpGenOverrides
// message.  Right now these only apply to the C++ API.
// TODO(josh11b): In the future there will be a common set of overrides
// and per-client-language overrides.
//
// WARNING: Be *very* careful using these features -- these overrides
// can change the semantics of existing code.  These changes may need
// to wait until a major release of TensorFlow to avoid breaking our
// compatibility promises.
type OpGenOverride struct {
	// Name of the op to apply overrides to.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Do not include this op in the generated API.
	// If `skip` is true, all other overrides are ignored for this op.
	Skip bool `protobuf:"varint,2,opt,name=skip,proto3" json:"skip,omitempty"`
	// Hide this op by putting it into an internal namespace (or whatever
	// is appropriate in the target language).
	Hide bool `protobuf:"varint,3,opt,name=hide,proto3" json:"hide,omitempty"`
	// Use a different name in the API than the op's name. Note that
	// the op's name in `backticks` will also be replaced in the docs.
	RenameTo string `protobuf:"bytes,4,opt,name=rename_to,json=renameTo,proto3" json:"rename_to,omitempty"`
	// Create *additional* API endpoints with different names (contrast
	// with rename_to, which affects the original name).
	Alias        []string                     `protobuf:"bytes,5,rep,name=alias" json:"alias,omitempty"`
	AttrDefault  []*OpGenOverride_AttrDefault `protobuf:"bytes,6,rep,name=attr_default,json=attrDefault" json:"attr_default,omitempty"`
	AttrRename   []*OpGenOverride_Rename      `protobuf:"bytes,7,rep,name=attr_rename,json=attrRename" json:"attr_rename,omitempty"`
	InputRename  []*OpGenOverride_Rename      `protobuf:"bytes,8,rep,name=input_rename,json=inputRename" json:"input_rename,omitempty"`
	OutputRename []*OpGenOverride_Rename      `protobuf:"bytes,9,rep,name=output_rename,json=outputRename" json:"output_rename,omitempty"`
}

func (m *OpGenOverride) Reset()                    { *m = OpGenOverride{} }
func (*OpGenOverride) ProtoMessage()               {}
func (*OpGenOverride) Descriptor() ([]byte, []int) { return fileDescriptorOpGenOverrides, []int{0} }

func (m *OpGenOverride) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *OpGenOverride) GetSkip() bool {
	if m != nil {
		return m.Skip
	}
	return false
}

func (m *OpGenOverride) GetHide() bool {
	if m != nil {
		return m.Hide
	}
	return false
}

func (m *OpGenOverride) GetRenameTo() string {
	if m != nil {
		return m.RenameTo
	}
	return ""
}

func (m *OpGenOverride) GetAlias() []string {
	if m != nil {
		return m.Alias
	}
	return nil
}

func (m *OpGenOverride) GetAttrDefault() []*OpGenOverride_AttrDefault {
	if m != nil {
		return m.AttrDefault
	}
	return nil
}

func (m *OpGenOverride) GetAttrRename() []*OpGenOverride_Rename {
	if m != nil {
		return m.AttrRename
	}
	return nil
}

func (m *OpGenOverride) GetInputRename() []*OpGenOverride_Rename {
	if m != nil {
		return m.InputRename
	}
	return nil
}

func (m *OpGenOverride) GetOutputRename() []*OpGenOverride_Rename {
	if m != nil {
		return m.OutputRename
	}
	return nil
}

// Map the name of an attr to a new default value to use.  This
// default will be used when creating new graphs, as opposed to the
// default in the OpDef, which will be used when interpreting old
// GraphDefs.  If this attr is also renamed (using attr_rename
// below), use the original name of the attr.
type OpGenOverride_AttrDefault struct {
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value *tensorflow5.AttrValue `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *OpGenOverride_AttrDefault) Reset()      { *m = OpGenOverride_AttrDefault{} }
func (*OpGenOverride_AttrDefault) ProtoMessage() {}
func (*OpGenOverride_AttrDefault) Descriptor() ([]byte, []int) {
	return fileDescriptorOpGenOverrides, []int{0, 0}
}

func (m *OpGenOverride_AttrDefault) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *OpGenOverride_AttrDefault) GetValue() *tensorflow5.AttrValue {
	if m != nil {
		return m.Value
	}
	return nil
}

// Change the name used to access attrs/inputs/outputs in the API
// from what is used in the GraphDef.  Note that these names in
// `backticks` will also be replaced in the docs.
type OpGenOverride_Rename struct {
	From string `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To   string `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
}

func (m *OpGenOverride_Rename) Reset()      { *m = OpGenOverride_Rename{} }
func (*OpGenOverride_Rename) ProtoMessage() {}
func (*OpGenOverride_Rename) Descriptor() ([]byte, []int) {
	return fileDescriptorOpGenOverrides, []int{0, 1}
}

func (m *OpGenOverride_Rename) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *OpGenOverride_Rename) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

type OpGenOverrides struct {
	Op []*OpGenOverride `protobuf:"bytes,1,rep,name=op" json:"op,omitempty"`
}

func (m *OpGenOverrides) Reset()                    { *m = OpGenOverrides{} }
func (*OpGenOverrides) ProtoMessage()               {}
func (*OpGenOverrides) Descriptor() ([]byte, []int) { return fileDescriptorOpGenOverrides, []int{1} }

func (m *OpGenOverrides) GetOp() []*OpGenOverride {
	if m != nil {
		return m.Op
	}
	return nil
}

func init() {
	proto.RegisterType((*OpGenOverride)(nil), "tensorflow.OpGenOverride")
	proto.RegisterType((*OpGenOverride_AttrDefault)(nil), "tensorflow.OpGenOverride.AttrDefault")
	proto.RegisterType((*OpGenOverride_Rename)(nil), "tensorflow.OpGenOverride.Rename")
	proto.RegisterType((*OpGenOverrides)(nil), "tensorflow.OpGenOverrides")
}
func (this *OpGenOverride) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*OpGenOverride)
	if !ok {
		that2, ok := that.(OpGenOverride)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if this.Name != that1.Name {
		return false
	}
	if this.Skip != that1.Skip {
		return false
	}
	if this.Hide != that1.Hide {
		return false
	}
	if this.RenameTo != that1.RenameTo {
		return false
	}
	if len(this.Alias) != len(that1.Alias) {
		return false
	}
	for i := range this.Alias {
		if this.Alias[i] != that1.Alias[i] {
			return false
		}
	}
	if len(this.AttrDefault) != len(that1.AttrDefault) {
		return false
	}
	for i := range this.AttrDefault {
		if !this.AttrDefault[i].Equal(that1.AttrDefault[i]) {
			return false
		}
	}
	if len(this.AttrRename) != len(that1.AttrRename) {
		return false
	}
	for i := range this.AttrRename {
		if !this.AttrRename[i].Equal(that1.AttrRename[i]) {
			return false
		}
	}
	if len(this.InputRename) != len(that1.InputRename) {
		return false
	}
	for i := range this.InputRename {
		if !this.InputRename[i].Equal(that1.InputRename[i]) {
			return false
		}
	}
	if len(this.OutputRename) != len(that1.OutputRename) {
		return false
	}
	for i := range this.OutputRename {
		if !this.OutputRename[i].Equal(that1.OutputRename[i]) {
			return false
		}
	}
	return true
}
func (this *OpGenOverride_AttrDefault) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*OpGenOverride_AttrDefault)
	if !ok {
		that2, ok := that.(OpGenOverride_AttrDefault)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if this.Name != that1.Name {
		return false
	}
	if !this.Value.Equal(that1.Value) {
		return false
	}
	return true
}
func (this *OpGenOverride_Rename) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*OpGenOverride_Rename)
	if !ok {
		that2, ok := that.(OpGenOverride_Rename)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if this.From != that1.From {
		return false
	}
	if this.To != that1.To {
		return false
	}
	return true
}
func (this *OpGenOverrides) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*OpGenOverrides)
	if !ok {
		that2, ok := that.(OpGenOverrides)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if len(this.Op) != len(that1.Op) {
		return false
	}
	for i := range this.Op {
		if !this.Op[i].Equal(that1.Op[i]) {
			return false
		}
	}
	return true
}
func (this *OpGenOverride) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 13)
	s = append(s, "&tensorflow.OpGenOverride{")
	s = append(s, "Name: "+fmt.Sprintf("%#v", this.Name)+",\n")
	s = append(s, "Skip: "+fmt.Sprintf("%#v", this.Skip)+",\n")
	s = append(s, "Hide: "+fmt.Sprintf("%#v", this.Hide)+",\n")
	s = append(s, "RenameTo: "+fmt.Sprintf("%#v", this.RenameTo)+",\n")
	s = append(s, "Alias: "+fmt.Sprintf("%#v", this.Alias)+",\n")
	if this.AttrDefault != nil {
		s = append(s, "AttrDefault: "+fmt.Sprintf("%#v", this.AttrDefault)+",\n")
	}
	if this.AttrRename != nil {
		s = append(s, "AttrRename: "+fmt.Sprintf("%#v", this.AttrRename)+",\n")
	}
	if this.InputRename != nil {
		s = append(s, "InputRename: "+fmt.Sprintf("%#v", this.InputRename)+",\n")
	}
	if this.OutputRename != nil {
		s = append(s, "OutputRename: "+fmt.Sprintf("%#v", this.OutputRename)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *OpGenOverride_AttrDefault) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&tensorflow.OpGenOverride_AttrDefault{")
	s = append(s, "Name: "+fmt.Sprintf("%#v", this.Name)+",\n")
	if this.Value != nil {
		s = append(s, "Value: "+fmt.Sprintf("%#v", this.Value)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *OpGenOverride_Rename) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&tensorflow.OpGenOverride_Rename{")
	s = append(s, "From: "+fmt.Sprintf("%#v", this.From)+",\n")
	s = append(s, "To: "+fmt.Sprintf("%#v", this.To)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *OpGenOverrides) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&tensorflow.OpGenOverrides{")
	if this.Op != nil {
		s = append(s, "Op: "+fmt.Sprintf("%#v", this.Op)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringOpGenOverrides(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *OpGenOverride) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OpGenOverride) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Name) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintOpGenOverrides(dAtA, i, uint64(len(m.Name)))
		i += copy(dAtA[i:], m.Name)
	}
	if m.Skip {
		dAtA[i] = 0x10
		i++
		if m.Skip {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if m.Hide {
		dAtA[i] = 0x18
		i++
		if m.Hide {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if len(m.RenameTo) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintOpGenOverrides(dAtA, i, uint64(len(m.RenameTo)))
		i += copy(dAtA[i:], m.RenameTo)
	}
	if len(m.Alias) > 0 {
		for _, s := range m.Alias {
			dAtA[i] = 0x2a
			i++
			l = len(s)
			for l >= 1<<7 {
				dAtA[i] = uint8(uint64(l)&0x7f | 0x80)
				l >>= 7
				i++
			}
			dAtA[i] = uint8(l)
			i++
			i += copy(dAtA[i:], s)
		}
	}
	if len(m.AttrDefault) > 0 {
		for _, msg := range m.AttrDefault {
			dAtA[i] = 0x32
			i++
			i = encodeVarintOpGenOverrides(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if len(m.AttrRename) > 0 {
		for _, msg := range m.AttrRename {
			dAtA[i] = 0x3a
			i++
			i = encodeVarintOpGenOverrides(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if len(m.InputRename) > 0 {
		for _, msg := range m.InputRename {
			dAtA[i] = 0x42
			i++
			i = encodeVarintOpGenOverrides(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if len(m.OutputRename) > 0 {
		for _, msg := range m.OutputRename {
			dAtA[i] = 0x4a
			i++
			i = encodeVarintOpGenOverrides(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func (m *OpGenOverride_AttrDefault) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OpGenOverride_AttrDefault) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Name) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintOpGenOverrides(dAtA, i, uint64(len(m.Name)))
		i += copy(dAtA[i:], m.Name)
	}
	if m.Value != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintOpGenOverrides(dAtA, i, uint64(m.Value.Size()))
		n1, err := m.Value.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	return i, nil
}

func (m *OpGenOverride_Rename) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OpGenOverride_Rename) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.From) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintOpGenOverrides(dAtA, i, uint64(len(m.From)))
		i += copy(dAtA[i:], m.From)
	}
	if len(m.To) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintOpGenOverrides(dAtA, i, uint64(len(m.To)))
		i += copy(dAtA[i:], m.To)
	}
	return i, nil
}

func (m *OpGenOverrides) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OpGenOverrides) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Op) > 0 {
		for _, msg := range m.Op {
			dAtA[i] = 0xa
			i++
			i = encodeVarintOpGenOverrides(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func encodeFixed64OpGenOverrides(dAtA []byte, offset int, v uint64) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	dAtA[offset+4] = uint8(v >> 32)
	dAtA[offset+5] = uint8(v >> 40)
	dAtA[offset+6] = uint8(v >> 48)
	dAtA[offset+7] = uint8(v >> 56)
	return offset + 8
}
func encodeFixed32OpGenOverrides(dAtA []byte, offset int, v uint32) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	return offset + 4
}
func encodeVarintOpGenOverrides(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *OpGenOverride) Size() (n int) {
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovOpGenOverrides(uint64(l))
	}
	if m.Skip {
		n += 2
	}
	if m.Hide {
		n += 2
	}
	l = len(m.RenameTo)
	if l > 0 {
		n += 1 + l + sovOpGenOverrides(uint64(l))
	}
	if len(m.Alias) > 0 {
		for _, s := range m.Alias {
			l = len(s)
			n += 1 + l + sovOpGenOverrides(uint64(l))
		}
	}
	if len(m.AttrDefault) > 0 {
		for _, e := range m.AttrDefault {
			l = e.Size()
			n += 1 + l + sovOpGenOverrides(uint64(l))
		}
	}
	if len(m.AttrRename) > 0 {
		for _, e := range m.AttrRename {
			l = e.Size()
			n += 1 + l + sovOpGenOverrides(uint64(l))
		}
	}
	if len(m.InputRename) > 0 {
		for _, e := range m.InputRename {
			l = e.Size()
			n += 1 + l + sovOpGenOverrides(uint64(l))
		}
	}
	if len(m.OutputRename) > 0 {
		for _, e := range m.OutputRename {
			l = e.Size()
			n += 1 + l + sovOpGenOverrides(uint64(l))
		}
	}
	return n
}

func (m *OpGenOverride_AttrDefault) Size() (n int) {
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovOpGenOverrides(uint64(l))
	}
	if m.Value != nil {
		l = m.Value.Size()
		n += 1 + l + sovOpGenOverrides(uint64(l))
	}
	return n
}

func (m *OpGenOverride_Rename) Size() (n int) {
	var l int
	_ = l
	l = len(m.From)
	if l > 0 {
		n += 1 + l + sovOpGenOverrides(uint64(l))
	}
	l = len(m.To)
	if l > 0 {
		n += 1 + l + sovOpGenOverrides(uint64(l))
	}
	return n
}

func (m *OpGenOverrides) Size() (n int) {
	var l int
	_ = l
	if len(m.Op) > 0 {
		for _, e := range m.Op {
			l = e.Size()
			n += 1 + l + sovOpGenOverrides(uint64(l))
		}
	}
	return n
}

func sovOpGenOverrides(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozOpGenOverrides(x uint64) (n int) {
	return sovOpGenOverrides(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *OpGenOverride) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&OpGenOverride{`,
		`Name:` + fmt.Sprintf("%v", this.Name) + `,`,
		`Skip:` + fmt.Sprintf("%v", this.Skip) + `,`,
		`Hide:` + fmt.Sprintf("%v", this.Hide) + `,`,
		`RenameTo:` + fmt.Sprintf("%v", this.RenameTo) + `,`,
		`Alias:` + fmt.Sprintf("%v", this.Alias) + `,`,
		`AttrDefault:` + strings.Replace(fmt.Sprintf("%v", this.AttrDefault), "OpGenOverride_AttrDefault", "OpGenOverride_AttrDefault", 1) + `,`,
		`AttrRename:` + strings.Replace(fmt.Sprintf("%v", this.AttrRename), "OpGenOverride_Rename", "OpGenOverride_Rename", 1) + `,`,
		`InputRename:` + strings.Replace(fmt.Sprintf("%v", this.InputRename), "OpGenOverride_Rename", "OpGenOverride_Rename", 1) + `,`,
		`OutputRename:` + strings.Replace(fmt.Sprintf("%v", this.OutputRename), "OpGenOverride_Rename", "OpGenOverride_Rename", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *OpGenOverride_AttrDefault) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&OpGenOverride_AttrDefault{`,
		`Name:` + fmt.Sprintf("%v", this.Name) + `,`,
		`Value:` + strings.Replace(fmt.Sprintf("%v", this.Value), "AttrValue", "tensorflow5.AttrValue", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *OpGenOverride_Rename) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&OpGenOverride_Rename{`,
		`From:` + fmt.Sprintf("%v", this.From) + `,`,
		`To:` + fmt.Sprintf("%v", this.To) + `,`,
		`}`,
	}, "")
	return s
}
func (this *OpGenOverrides) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&OpGenOverrides{`,
		`Op:` + strings.Replace(fmt.Sprintf("%v", this.Op), "OpGenOverride", "OpGenOverride", 1) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringOpGenOverrides(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *OpGenOverride) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOpGenOverrides
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OpGenOverride: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OpGenOverride: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOpGenOverrides
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOpGenOverrides
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Skip", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOpGenOverrides
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Skip = bool(v != 0)
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hide", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOpGenOverrides
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Hide = bool(v != 0)
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RenameTo", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOpGenOverrides
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOpGenOverrides
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RenameTo = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Alias", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOpGenOverrides
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOpGenOverrides
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Alias = append(m.Alias, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AttrDefault", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOpGenOverrides
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthOpGenOverrides
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AttrDefault = append(m.AttrDefault, &OpGenOverride_AttrDefault{})
			if err := m.AttrDefault[len(m.AttrDefault)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AttrRename", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOpGenOverrides
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthOpGenOverrides
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AttrRename = append(m.AttrRename, &OpGenOverride_Rename{})
			if err := m.AttrRename[len(m.AttrRename)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InputRename", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOpGenOverrides
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthOpGenOverrides
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.InputRename = append(m.InputRename, &OpGenOverride_Rename{})
			if err := m.InputRename[len(m.InputRename)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OutputRename", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOpGenOverrides
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthOpGenOverrides
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OutputRename = append(m.OutputRename, &OpGenOverride_Rename{})
			if err := m.OutputRename[len(m.OutputRename)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipOpGenOverrides(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthOpGenOverrides
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *OpGenOverride_AttrDefault) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOpGenOverrides
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AttrDefault: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AttrDefault: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOpGenOverrides
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOpGenOverrides
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOpGenOverrides
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthOpGenOverrides
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Value == nil {
				m.Value = &tensorflow5.AttrValue{}
			}
			if err := m.Value.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipOpGenOverrides(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthOpGenOverrides
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *OpGenOverride_Rename) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOpGenOverrides
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Rename: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Rename: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field From", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOpGenOverrides
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOpGenOverrides
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.From = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field To", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOpGenOverrides
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOpGenOverrides
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.To = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipOpGenOverrides(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthOpGenOverrides
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *OpGenOverrides) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOpGenOverrides
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OpGenOverrides: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OpGenOverrides: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Op", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOpGenOverrides
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthOpGenOverrides
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Op = append(m.Op, &OpGenOverride{})
			if err := m.Op[len(m.Op)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipOpGenOverrides(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthOpGenOverrides
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipOpGenOverrides(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowOpGenOverrides
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowOpGenOverrides
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowOpGenOverrides
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthOpGenOverrides
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowOpGenOverrides
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipOpGenOverrides(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthOpGenOverrides = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowOpGenOverrides   = fmt.Errorf("proto: integer overflow")
)

func init() {
	proto.RegisterFile("protobuf/tensorflow/core/framework/op_gen_overrides.proto", fileDescriptorOpGenOverrides)
}

var fileDescriptorOpGenOverrides = []byte{
	// 418 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x4f, 0x6b, 0xd4, 0x40,
	0x14, 0xc0, 0x77, 0xb2, 0x7f, 0xdc, 0xbc, 0x6c, 0x7b, 0x18, 0x14, 0xc6, 0x15, 0x86, 0x50, 0x10,
	0xa2, 0x96, 0x04, 0xea, 0x49, 0x3c, 0xd5, 0x3f, 0xe8, 0xc9, 0xc2, 0x20, 0x5e, 0xc3, 0xd4, 0x9d,
	0x68, 0x68, 0x36, 0x2f, 0x4c, 0x26, 0xed, 0xd5, 0x8f, 0xe0, 0xc5, 0xef, 0xe0, 0x47, 0xf1, 0xd8,
	0xa3, 0x47, 0x37, 0x5e, 0x3c, 0xf6, 0x23, 0xc8, 0xcc, 0x6c, 0xd9, 0x2d, 0x74, 0xa1, 0xb7, 0xf7,
	0x5e, 0xde, 0xef, 0x37, 0xef, 0xf1, 0x02, 0x2f, 0x1a, 0x8d, 0x06, 0x4f, 0xbb, 0x22, 0x33, 0xaa,
	0x6e, 0x51, 0x17, 0x15, 0x5e, 0x64, 0x9f, 0x51, 0xab, 0xac, 0xd0, 0x72, 0xa9, 0x2e, 0x50, 0x9f,
	0x65, 0xd8, 0xe4, 0x5f, 0x54, 0x9d, 0xe3, 0xb9, 0xd2, 0xba, 0x5c, 0xa8, 0x36, 0x75, 0x0c, 0x85,
	0x0d, 0x31, 0x7f, 0xba, 0x9b, 0x96, 0xc6, 0xe8, 0xfc, 0x5c, 0x56, 0x9d, 0xf2, 0xdc, 0xc1, 0x8f,
	0x11, 0xec, 0x9d, 0x34, 0xef, 0x54, 0x7d, 0xb2, 0x16, 0x52, 0x0a, 0xa3, 0x5a, 0x2e, 0x15, 0x23,
	0x31, 0x49, 0x42, 0xe1, 0x62, 0x5b, 0x6b, 0xcf, 0xca, 0x86, 0x05, 0x31, 0x49, 0xa6, 0xc2, 0xc5,
	0xb6, 0xf6, 0xb5, 0x5c, 0x28, 0x36, 0xf4, 0x35, 0x1b, 0xd3, 0x47, 0x10, 0x6a, 0x65, 0x89, 0xdc,
	0x20, 0x1b, 0x39, 0xc1, 0xd4, 0x17, 0x3e, 0x22, 0xbd, 0x0f, 0x63, 0x59, 0x95, 0xb2, 0x65, 0xe3,
	0x78, 0x98, 0x84, 0xc2, 0x27, 0xf4, 0x3d, 0xcc, 0xdc, 0x50, 0x0b, 0x55, 0xc8, 0xae, 0x32, 0x6c,
	0x12, 0x0f, 0x93, 0xe8, 0xe8, 0x71, 0xba, 0xd9, 0x21, 0xbd, 0x31, 0x5f, 0x7a, 0x6c, 0x8c, 0x7e,
	0xe3, 0x9b, 0x45, 0x24, 0x37, 0x09, 0x3d, 0x06, 0x97, 0xe6, 0xfe, 0x41, 0x76, 0xcf, 0x89, 0xe2,
	0xdd, 0x22, 0xe1, 0xfa, 0x04, 0x58, 0xc8, 0xc7, 0xf4, 0x35, 0xcc, 0xca, 0xba, 0xe9, 0xcc, 0xb5,
	0x63, 0x7a, 0x47, 0x47, 0xe4, 0xa8, 0xb5, 0xe4, 0x2d, 0xec, 0x61, 0x67, 0xb6, 0x2c, 0xe1, 0x1d,
	0x2d, 0x33, 0x8f, 0xf9, 0x6c, 0xfe, 0x01, 0xa2, 0xad, 0x55, 0x6f, 0x3d, 0xcb, 0x33, 0x18, 0xbb,
	0x5b, 0xba, 0xbb, 0x44, 0x47, 0x0f, 0xb6, 0x5f, 0xb0, 0xec, 0x27, 0xfb, 0x51, 0xf8, 0x9e, 0xf9,
	0x21, 0x4c, 0xd6, 0x03, 0x52, 0x18, 0x15, 0x1a, 0x97, 0xd7, 0x2a, 0x1b, 0xd3, 0x7d, 0x08, 0x0c,
	0x3a, 0x4f, 0x28, 0x02, 0x83, 0x07, 0x2f, 0x61, 0xff, 0xc6, 0x8c, 0x2d, 0x7d, 0x02, 0x01, 0x36,
	0x8c, 0xb8, 0x5d, 0x1e, 0xee, 0xdc, 0x45, 0x04, 0xd8, 0xbc, 0x3a, 0xbc, 0x5c, 0xf1, 0xc1, 0xef,
	0x15, 0x1f, 0x5c, 0xad, 0x38, 0xf9, 0xd6, 0x73, 0xf2, 0xb3, 0xe7, 0xe4, 0x57, 0xcf, 0xc9, 0x65,
	0xcf, 0xc9, 0x9f, 0x9e, 0x93, 0x7f, 0x3d, 0x1f, 0x5c, 0xf5, 0x9c, 0x7c, 0xff, 0xcb, 0x07, 0xa7,
	0x13, 0xf7, 0x27, 0x3e, 0xff, 0x1f, 0x00, 0x00, 0xff, 0xff, 0x18, 0xd1, 0x5d, 0x6a, 0xfe, 0x02,
	0x00, 0x00,
}
